// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwptcCV3eRGd96H3CJVpJK_l_rAELvT3Q',
    appId: '1:685659054230:web:b330c5f8ba803bf196e2b7',
    messagingSenderId: '685659054230',
    projectId: 'mediaapp-a6021',
    authDomain: 'mediaapp-a6021.firebaseapp.com',
    storageBucket: 'mediaapp-a6021.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBukXsIsoZVsMZalgECxggIQeoqcxkpN_s',
    appId: '1:685659054230:android:589f222002bfb68f96e2b7',
    messagingSenderId: '685659054230',
    projectId: 'mediaapp-a6021',
    storageBucket: 'mediaapp-a6021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPc8-4Bk4NA7IPdjYl5GL6H6AoZ9L7QA',
    appId: '1:685659054230:ios:4202f65259ab12d296e2b7',
    messagingSenderId: '685659054230',
    projectId: 'mediaapp-a6021',
    storageBucket: 'mediaapp-a6021.appspot.com',
    iosBundleId: 'com.example.mediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPc8-4Bk4NA7IPdjYl5GL6H6AoZ9L7QA',
    appId: '1:685659054230:ios:3261bc45318354bd96e2b7',
    messagingSenderId: '685659054230',
    projectId: 'mediaapp-a6021',
    storageBucket: 'mediaapp-a6021.appspot.com',
    iosBundleId: 'com.example.mediaapp.RunnerTests',
  );
}
